{{- $fullName := include "todo_app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "todo_app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    -
      host: {{ .Values.host }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          -
            pathType: Prefix
            path: {{ .path }}
            backend:
              service: 
                name: {{ $fullName }}-{{ .serviceSuffix }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
