---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo_app.fullname" . }}-server
  labels:
    {{- include "todo_app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo_app.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.server.labels | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo_app.fullname" . }}-redis
  labels:
    {{- include "todo_app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo_app.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.redis.labels | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo_app.fullname" . }}-front
  labels:
    {{- include "todo_app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.front.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo_app.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.front.labels | nindent 4 }}
