apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "todo_app.fullname" . }}-redis
  labels:
    {{- include "todo_app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "todo_app.fullname" . }}-redis
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo_app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo_app.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.redis.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.redis.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.redis.port }}
              protocol: TCP
          command:
            - sh
            - '-c'
            - >-
              echo PASS=${DB_PASS}; redis-server --save 30 1 --requirepass
              ${DB_PASS}
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo_app.fullname" . }}
                  key: DB_PASS
                  optional: false
          {{- if .Values.persistentStorage.enabled }}
          volumeMounts:
            -
              name: claim1
              mountPath: /data
          {{- end }}
  {{- with .Values.persistentStorage }}
  {{- if .enabled }}
  volumeClaimTemplates:
  - metadata:
      name: claim1
    spec:
      accessModes:
        {{- toYaml .accessModes | nindent 8 }}
      storageClassName: {{ .storageClassName }}
      resources:
        requests:
          storage: {{ .storage }}
  {{- end }}
  {{- end }}